backend/src/chatbot/chatbot.controller.ts
backend/src/chatbot/chatbot.service.ts
frontend/src/app/chatbot/page.tsx

- 사용자 입력 검증 및 정제 함수 구현
- 위험한 프롬프트 패턴 자동 차단
- 입력 길이 제한 (500자) 및 특수 문자 제거
- 안전한 프롬프트 구조로 변경
Fix: 메시지 길이 제한 통일 (1000자 → 500자)
Design: 프론트엔드 마크다운 지원 추가
- **굵은 글씨**, *기울임체*,  형식 지원
- AI 응답의 텍스트 포맷팅 개선
Refactor: 챗봇 보안 아키텍처 개선

Feat: 챗봇 프롬프트 인젝션 방지 기능 추가

---

backend/src/auth/auth.controller.ts
backend/src/config/environment.ts
backend/src/server.ts
backend/src/types/auth.ts
backend/src/users/users.service.ts
frontend/src/app/confirm-email/page.tsx
frontend/src/app/signup/page.tsx

- 환경설정(environment.ts) 추가로 프론트/백엔드 URL을 개발/운영에 따라 자동 분기
- 회원가입/이메일 인증/소셜로그인 시 환경에 맞는 링크로 동작
- confirm-email, signup 등 페이지의 디버깅용 console.log 제거
- 관련 컨트롤러, 서비스 코드 환경 분기 적용 및 리팩토링

Refactor: 환경에 따라 이메일 인증/로그인 링크 동적 생성 및 디버깅 로그 제거

---

backend/src/auth/auth.controller.ts

- 이메일 가입 시 'email_signup' 저장
- 구글 OAuth 가입 시 'google_oauth' 저장
- 회원가입, OAuth 콜백, 이메일 인증 확인 로직 수정

FIX: password_hash 필드에 가입자 유형 저장 로직 추가

---

backend/src/auth/auth.controller.ts

- /google-user 엔드포인트에 지갑 생성 로직 추가
- private_key_encrypted 필드에 암호화된 개인키 저장
- wallet_address 필드에 생성된 지갑 주소 저장

FIX: Google OAuth 사용자 생성 시 private_key_encrypted 필드 누락 오류 수정

---

backend/src/concerts/concerts.controller.ts
backend/src/concerts/concerts.model.ts
backend/src/concerts/concerts.service.ts
backend/src/venues/venues.controller.ts
backend/src/venues/venues.service.ts
frontend/next.config.ts
frontend/src/app/admin/concert-create/page.tsx
frontend/src/app/admin/concerts/page.tsx

- 콘서트 등록 시 좌석 등급별 가격 설정 기능 구현
- 공연장 좌석 등급 조회 및 콘서트별 좌석 가격 관리 API 추가
- 관리자용 콘서트 목록 API 개선 (venues 정보 포함)
- 날짜 유효성 검사 및 안전한 날짜 처리 로직 구현
- Next.js 외부 이미지 도메인 허용 설정 추가
- 관리자 페이지 UI/UX 개선 (날짜 제약사항, 가격 설정 UI)

Feat: 콘서트 관리 시스템 개선 및 좌석 가격 설정 기능 추가

---

.gitignore
backend/src/chatbot/chatbot.service.ts
backend/src/concerts/concerts.service.ts
backend/src/tickets/tickets.service.ts

- 챗봇에서 다음 페이지 버튼 기능 개선 (구체적 페이지 번호 표시)
- location 컬럼 오류 수정: venues 테이블 조인으로 변경
- getUserTickets, getTicketById에서 올바른 venue 정보 조회
- ai-server/venv, backend 빌드 파일들 .gitignore 추가
- 페이지네이션 제안 버튼을 더 명확하게 개선

Feat: 챗봇 페이지네이션 기능 개선 및 DB 스키마 오류 수정

---

backend/src/concerts/concerts.controller.ts
backend/src/concerts/concerts.service.ts
frontend/src/app/layout/Navbar.tsx
frontend/src/app/page.tsx
frontend/src/app/search/page.tsx

- 전용 검색 결과 페이지 (/search) 구현
- 상단 navbar 검색 기능 활성화
- 백엔드 검색 API 엔드포인트 추가 (/concerts/search)
- 카테고리별 필터링 기능 구현
- 홈페이지 콘서트 둘러보기 섹션에 검색 버튼 추가
- 검색 결과 개수 표시 및 빈 결과 처리
- URL 파라미터 기반 검색 상태 관리

Feat: 검색 기능 구현 및 전용 검색 결과 페이지 추가

---

backend/src/chatbot/chatbot.service.ts
backend/src/concerts/concerts.service.ts
frontend/src/app/chatbot/page.tsx

- 모든 콘서트 목록 보기 기능 추가
- 과거 날짜 콘서트 검색 지원
- 페이지네이션에서 필터 조건 유지
- showAllConcerts 옵션으로 의도별 필터링

Feat: 챗봇 모든/과거 콘서트 검색 기능 추가 

---

frontend/src/app/concert/[slug]/components/BookingBox.tsx
frontend/src/app/concert/[slug]/components/ConcertHeader.tsx
frontend/src/app/concert/[slug]/page.tsx
frontend/src/app/concert/[slug]/types/index.ts
frontend/src/app/modal/OneTicketModal.tsx
package-lock.json
package.json

Feat : 회차 선택 및 예매일 시작일 시 버튼 활성화로 변경
Feat : 1인 1매 안내 모달창 추가

Feat : 회차 선택 및 예매일 시작일 시 버튼 활성화로 변경 /  Feat : 1인 1매 안내 모달창 추가

---

backend/src/users/users.controller.ts

프론트에서 성별구분방법
// API 호출 후
const residentNumber = response.data.residentNumber; // "9501011" const genderDigit = residentNumber.charAt(6); // "1"
if (genderDigit === "1" || genderDigit === "3") {
console.log("남성");
} else if (genderDigit === "2" || genderDigit === "4") {
console.log("여성");
}
테스트
curl -X GET "http://localhost:4000/users/resident-number/72f250b6-1eb2-4294-823d-b72cb45c0552" -H "Content-Type: application/json"
반환결과
{
"success": true,
"data": {
"residentNumber": "0101203"
},
"message": "주민번호 조회 성공"
}

Feat: 주민번호 7자리 복호화 API 및 프론트 성별구분 예시 추가

---

backend/src/cancellation_policies/cancellation_policies.service.ts
backend/src/chatbot/chatbot.service.ts
frontend/package-lock.json
frontend/package.json
frontend/src/app/layout/ChatbotModal.tsx

- 챗봇 UI 개선 (입력창 하단 고정, 회색 바탕 제거, 모던한 디자인)
- 콘서트 목록 테이블 불필요한 공백 제거
- 로그인 사용자 인식 문제 해결 (Bearer 토큰 방식으로 변경)
- 취소정책 시기별 정렬 기능 추가

Fix: 챗봇 기능 개선 - UI 변경, 테이블 포맷팅, 사용자 인식, 취소정책 정렬

---

backend/src/users/users.controller.ts

- feat: dashboard API에서 프로필, 티켓, 좋아요 목록을 한 번에 조회 
- feat: 좋아요 목록 조회 함수 추가 (getUserFavorites) 
- refactor: 통계 정보 구조화 (tickets, favorites)  
- ✅ 기능 요약: - 기존: 3개 API 호출 (프로필, 티켓, 좋아요) 
- 개선: 1개 API 호출로 통합 (dashboard) 
- 응답 구조: { profile, tickets, favorites, stats }

Feat: 마이페이지 dashboard API에 좋아요 목록 기능 추가 

---

backend/src/blockchain/blockchain.service.ts
blockchain/scripts/fundUser.ts

npx hardhat clean
npx hardhat compile
npx hardhat node
새 터미널에서 아래처럼실행
npx hardhat run --network localhost scripts/deploy.ts
결제실패시에 백엔드에서 나오는 🔍 실제 사용자 지갑 주소:  <<< 이 주소 값으로 충전하면됨)
npx hardhat run --network localhost scripts/fundUser.ts

FEAT: Update blockchain scripts for wallet address debugging

---

frontend/src/app/components/Payment.tsx
frontend/src/app/concert/[slug]/page.tsx
frontend/src/app/mypage/page.tsx
frontend/src/lib/apiClient.ts

Design : 결제 페이지 UI 수정 - 페이지 폭 수정 및 위 상단 step 디자인 1차 수정
Feat : 마이페이지 UI 수정 및 티켓 취소 요청 - UI 전체적으로 수정, 티켓 취소 api 요청

Design : 결제 페이지 UI 수정 / Feat : 마이페이지 UI 수정 및 티켓 취소 요청

---

backend/src/blockchain/verification.service.ts
backend/src/tickets/tickets.controller.ts
backend/src/tickets/tickets.service.ts
backend/src/users/users.controller.ts
test_verification.js

- FIX: DB nft_token_id 문자열 타입 불일치 문제 해결
- FEAT: 실제 데이터 기반 블록체인 검증 테스트 자동화
- TEST: 소유권, 사용상태, 얼굴인증, 취소, 민팅자격 검증 완료
- DOCS: 블록체인 검증 테스트 방법 및 보안 시나리오 문서화
테스트시에 DB에 사용자(user),티켓(tickets,)nft_token_id(민팅된 티켓) 데이터가 있어야함
테스트방법:
1.사용자 목록확인
curl http://localhost:4000/users
2.특정 사용자의 티켓 확인 
curl http://localhost:4000/tickets/my-tickets/{userId}
3.test_verification.js 파일에서 TEST_DATA에 필드들의 값을 supabase ticket 테이블에 있는것중 하나로 변경
4.검증 블록체인+DB
node test_verification.js
모든 검증(소유권, 사용상태, 얼굴인증, 취소, 민팅자격, 종합검증)이 자동으로 실행됨
시나리오 DB해킹:
공격자: DB에서 티켓 정보 삭제
결과:
- DB: "티켓 없음"
- 블록체인: "토큰 1번은 0xabc... 소유"
- 검증: 실패 (DB 불일치 감지)
블록체인 해킹(거의 불가능):
공격자: 블록체인 조작 시도
결과:
- 51% 공격 필요 (현실적으로 불가능)
- 비용이 너무 큼
시나리오 정상 작동:
사용자: 정상적인 티켓 사용
결과:
- DB: "티켓 존재, 사용 안됨"
- 블록체인: "토큰 1번, 사용 안됨"
- 검증: 성공 ✅

FEAT: 블록체인 검증 로직 개선 및 보안 테스트 완료

---

README.md
ai-server/main.py
backend/src/config/environment.ts
test_verification.js

- backend/src/config/environment.ts: FRONTEND_URL/BACKEND_URL 환경변수 사용
- ai-server/main.py: SERVER_IP 환경변수 사용
- test_verification.js: BACKEND_URL 환경변수 사용
- README.md: 새로운 환경변수들 문서화
- 모든 하드코딩된 URL 제거 및 환경변수 검증 로직 추가

REFACTOR: 하드코딩된 URL들을 환경변수로 변경

---

backend/src/blockchain/blockchain.service.ts
backend/src/blockchain/verification.service.ts
backend/src/tickets/tickets.controller.ts
backend/src/tickets/tickets.service.ts
frontend/src/app/qr-scanner/page.tsx

- 스마트 컨트랙트가 얼굴 인증을 요구하므로, 입장 처리 전에 더미 얼굴 해시를 등록하고 인증 통과 처리
- 각 트랜잭션 후 wait() 호출 및 1초 간격 추가로 nonce 충돌 방지
- 블록체인 입장 처리가 성공한 경우에만 DB 업데이트 수행
- 블록체인 실패 시 DB 상태 불일치 방지
- 얼굴 인증 요구사항 자동 충족
- Nonce 오류로 인한 트랜잭션 실패 해결
- 블록체인과 DB 상태 일관성 보장
- 회원가입 시 DB에 저장되는 얼굴 임베딩값을 해시화하여 블록체인의 faceHash 변수에 저장
- 현재는 더미 해시를 사용하지만, 실제 얼굴 인증 시에는 저장된 faceHash와 비교하여 검증
- 검증은 tickets(tokenId).isFaceVerified로 수행

FIX: QR 코드 인증 시 얼굴 인증 자동 처리 및 nonce 오류 해결

---

frontend/src/app/components/Payment.tsx
frontend/src/app/components/PaymentComplete.tsx
frontend/src/app/components/SeatGrid.tsx
frontend/src/app/components/SeatSelection.tsx
frontend/src/app/components/Sidebar.tsx
frontend/src/app/modal/CaptchaModal.tsx
frontend/src/app/modal/ConfirmModal.tsx
frontend/src/app/seat/page.tsx
frontend/src/types/ticket.ts
frontend/tsconfig.json

Feat: 블록체인 티켓 민팅 결과 타입 TicketMintResult 추가
Feat: 좌석 선택 페이지에 ConfirmModal 인증 기능 추가
[Feat: 결제페이지에서 좌석 페이지로 이전 기능 및 확인 모달(ConfirmModal) 추가]
[Feat: 결제페이지에서 좌석 페이지로 이전 기능 및 확인 모달(ConfirmModal) 추가]
[Design : VIP 좌석 구역 색깔 구분]
[Chore: tsconfig.json에 types 디렉토리 포함 설정 추가]

블록체인 티켓 타입 정의 및 결제→좌석 이전 모달 기능 추가, VIP 좌석 디자인 개선

---

frontend/src/app/components/SeatGrid.tsx

- VIP석 선택 시에도 분홍색 계열 스타일 유지
- 선택된 VIP석은 진한 분홍색(bg-pink-300)과 테두리 효과 적용
- 스타일링 조건 순서 변경으로 VIP석 스타일 우선 적용

feat: VIP석 좌석 선택 시 스타일링 개선

---

backend/src/blockchain/verification.service.ts
backend/src/tickets/tickets.service.ts

- QR 코드에 지갑 주소 포함 (DB users.wallet_address → QR walletAddress)
- 소유권 검증: QR walletAddress ↔ 블록체인 ownerOf(tokenId) 직접 비교
- 사용 상태: 블록체인 tickets(tokenId).isUsed (true/false)
- 얼굴 인증: 블록체인 tickets(tokenId).isFaceVerified (true/false)
- 취소 상태: 블록체인 isCancelled(tokenId) (true/false)
- 모든 검증을 100% 블록체인 상태 기반으로 변경
- DB는 UI 표시용 정보만 제공, 실제 검증은 블록체인에서만 수행

FEAT: 블록체인 중심 QR 코드 검증 시스템 구현

---

ai-server/requirements.txt
ai-server/services/face_service.py
ai-server/static/face_registerG.html
ai-server/static/face_verify.html
ai-server/utils/crypto_utils.py
ai-server/utils/io_utils.py
backend/src/auth/auth.controller.ts
blockchain/cache/solidity-files-cache.json
frontend/src/app/auth/callback/page.tsx
frontend/src/app/page.tsx

1. **Google OAuth 로그인 후 토큰 유지 문제 해결**
- 얼굴 등록 후 프론트엔드로 돌아오면 accessToken, refreshToken 을 localStorage 에 저장
- window.location.reload() 대신 router.replace('/') 로 이동하여 로그인 유지
2. **얼굴 등록/인증 암호화 로직 추가**
- 얼굴 등록 시:
- 임베딩을 AES 암호화하여 DB에 저장하도록 변경
- 얼굴 인증(로그인) 시:
- DB에서 암호화된 임베딩을 복호화 후 실시간 추출 임베딩과 비교
3. **HomePage useEffect 구조 수정**
- accessToken 이 있는 경우 getUserWithToken 호출 로직 안정화
✅ Google OAuth → 얼굴 등록 페이지 → 등록 완료 후 프론트 복귀 → 로그인 유지 여부  
✅ 얼굴 등록 시 DB에 암호화된 embedding 컬럼명 embedding_enc 저장 여부

🔒✨ Fix: Google OAuth 로그인 후 토큰 유지 + 얼굴 등록 임베딩 암호화/복호화 기능 추가

---

frontend/src/app/layout/Navbar.tsx
frontend/src/components/NFTTicket.tsx
frontend/src/components/RecentNFTTickets.tsx
frontend/src/types/ticket.ts

네비게이션바 - 티켓에서 드롭다운으로 티켓 정보 출력
NFTTicket.tsx - 큐알 정보 확대하는 기능 추가
RecentNFTTickets.tsx - 드롭다운 안에 들어갈 티켓 정보 NFTTicket.tsx로 가져오고 옆으로 넘기는 슬라이더 버튼 추가
ticket.ts - NFT 공연 티켓 정보를 타입 따로 분리해서 정의

Feat : 티켓 정보 드롭다운으로 출력 기능 추가

---

ai-server/services/face_service.py
ai-server/static/face_register.html
ai-server/static/face_registerG.html

1. 파일 업로드를 이용한 얼굴 등록 추가
2. 버튼 예외처리 추가 ex. 등록 중 파일 업로드 버튼 비활성화

feat: face_register html 수정 등

---

ai-server/utils/io_utils.py

- 얼굴 감지 임계값 완화: det_score_threshold=0.2로 조정
- 얼굴 각도 허용 범위 확대: yaw_threshold=60도로 증가
- Fallback 로직 추가: 첫 시도 실패 시 더 관대한 설정으로 재시도
- 상세한 디버깅 로그 추가로 문제 추적 가능
- CLAHE 파라미터 강화로 조명 보정 개선
프레임 처리 최적화:
- 90프레임 녹화 (3초 × 30fps)
- frame_skip=2 설정으로 3프레임 중 1프레임만 처리
- 결과: 30프레임만 분석, 60프레임 건너뛰기
회원가입 시 '유효한 얼굴을 찾을 수 없습니다' 오류 해결

FEAT: 얼굴 인식 성능 최적화 개선

---

backend/package-lock.json
backend/package.json
backend/src/concerts/concerts.controller.ts
backend/src/concerts/concerts.service.ts
frontend/src/app/concert/[slug]/hooks/useAuth.ts
frontend/src/app/concert/[slug]/hooks/useConcertData.ts
frontend/src/app/concert/[slug]/hooks/useFavorite.ts
frontend/src/app/concert/[slug]/page.tsx

성능 최적화 및 병목현상 제거로 응답속도 대폭 개선
- 기존 8초 이상 → 2-3초로 응답시간 60-70% 단축
- 병렬 처리 도입으로 순차 처리 방식의 병목현상 완전 제거
- 타임아웃 설정으로 무한 대기 문제 해결
- API 요청 타임아웃 설정 (3-5초)
- AbortController를 이용한 안전한 요청 취소
- 지연 로딩으로 우선순위 조정 (중복체크 1초, 찜하기 2초)
- 더 명확한 로딩 UI 및 에러 메시지 개선
- Promise.all을 이용한 병렬 처리 도입
* seat_prices와 cancellation_policies 동시 조회
* 기존 순차처리 방식에서 병렬처리로 전환하여 응답속도 3배 향상
- 데이터베이스 쿼리 최적화
* 필요한 컬럼만 SELECT하여 데이터 전송량 감소
* LIMIT 50으로 결과 수 제한하여 메모리 사용량 최적화
- Promise.race를 이용한 타임아웃 설정 (8초)
- 에러 처리 강화 및 안정성 향상
- frontend/src/app/concert/[slug]/hooks/useConcertData.ts
- frontend/src/app/concert/[slug]/hooks/useAuth.ts
- frontend/src/app/concert/[slug]/hooks/useFavorite.ts
- backend/src/concerts/concerts.service.ts
- backend/src/concerts/concerts.controller.ts
- 응답 속도 기존 8초에서 2-3초로 대폭 단축 (60-70% 개선)
- 안정성 크게 개선
- 사용자 경험 최적화 …

FEAT: 병목현상 제거

---

frontend/src/app/about/page.tsx
frontend/src/app/careers/page.tsx
frontend/src/app/contact/page.tsx
frontend/src/app/faq/page.tsx
frontend/src/app/guide/page.tsx
frontend/src/app/layout/Footer.tsx
frontend/src/app/mypage/page.tsx
frontend/src/app/notice/page.tsx
frontend/src/app/privacy/page.tsx
frontend/src/app/terms/page.tsx

- Footer 링크 페이지들 생성 (회사소개, 채용, 공지사항, FAQ, 예매가이드, 1:1문의, 이용약관, 개인정보처리방침)
- 마이페이지 상세보기 버튼 및 마우스오버 효과 문제 해결

FEAT: Footer 페이지들 생성 및 마이페이지 수정

---

backend/src/auth/auth.controller.ts
frontend/src/app/components/PaymentComplete.tsx
frontend/src/app/face-registration/page.tsx
frontend/src/app/layout/Navbar.tsx
frontend/src/app/login/page.tsx
frontend/src/app/modal/ConfirmModal.tsx
frontend/src/components/RecentNFTTickets.tsx
frontend/src/types/ticket.ts

- 얼굴 임베딩 검증을 위한 디버깅 로그 추가
- PaymentComplete 컴포넌트에서 팝업 닫고 부모 창으로 리다이렉트 수정
- 얼굴 등록 페이지 사용자 가이드 개선
- Navbar에서 취소된 티켓을 최근 티켓에서 제외하도록 수정
- 티켓 타입에 취소 상태 필드 추가
- 로그인 페이지에서 얼굴 임베딩 상태 디버깅 개선

FIX: 얼굴 인증 및 티켓 표시 문제 해결
